kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
  namespace: 'pl' # {"$kpt-set":"namespace"}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
